#define WS2812_DI_PIN D0
#define RGBLIGHT_LED_COUNT 100
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT	
#define RGBLIGHT_DEFAULT_HUE 212
#define RGBLIGHT_DEFAULT_VAL 24
#define ENCODER_RESOLUTION 4
#define RGBLIGHT_LAYERS